package org.example.drools

import org.example.Person

rule "מבוגר"
    when
        $person : Person(age >= 18)
    then
        System.out.println($person.getName() + ($person.getGender().equals("female") ? " היא מבוגרת" : " הוא מבוגר"));
        modify($person) { setAdult(true) }
end

rule "צעיר"
    when
        $person : Person(age < 18)
    then
        System.out.println($person.getName() + ($person.getGender().equals("female") ? " היא צעירה" : " הוא צעיר"));
        modify($person) { setAdult(false) }
end


rule "מגדר"
when
    $person : Person(gender != null)
then
    if ($person.getGender().equals("female")) {
        System.out.println($person.getName() + " היא נקבה.");
        modify($person) {
            setFemale(true)
        };
    } else{
        System.out.println($person.getName() + " הוא זכר.");
        modify($person) {
            setFemale(false)
        };
    }
end

